In [1]:
# read the simulated factor values

fact <- read.csv('factors.csv')
head(fact,20)

period regime regimeName      mrp          smb         hml         
1   1     0      Low Volatility   0.036375992  0.18330527  0.009807682
2   2     1      High Volatility -0.007027288  0.11146076 -0.066323909
3   3     1      High Volatility -0.020924587  0.25700416 -0.017613504
4   4     0      Low Volatility   0.165770713 -0.05539058 -0.010676344
5   5     0      Low Volatility  -0.024865562  0.04425650  0.034018862
6   6     0      Low Volatility   0.047413778  0.06721091 -0.020243420
7   7     0      Low Volatility   0.071379152 -0.08083119 -0.055199596
8   8     0      Low Volatility  -0.010067201 -0.02508647  0.065694993
9   9     0      Low Volatility   0.270711583  0.03858093  0.017653905
10 10     0      Low Volatility   0.247990657  0.08931008  0.162487523
11 11     0      Low Volatility   0.091252960  0.02046379  0.003647982
12 12     1      High Volatility -0.184480571  0.29632617  0.082302239
13 13     0      Low Volatility  -0.059102998 -0.05089042  0.070161914
14 14     1      High Volatility -0.149028547  0.02429038  0.069741253
15 15     1      High Volatility -0.137838491  0.05860076 -0.058427487
16 16     0      Low Volatility   0.099017759 -0.18082550  0.142529862
17 17     0      Low Volatility   0.105120296 -0.05762067  0.163672490
18 18     1      High Volatility  0.014142180  0.05264550 -0.055883738
19 19     1      High Volatility -0.031553195  0.04845196  0.173665241
20 20     1      High Volatility  0.092152261  0.43193617  0.274777491

In [2]:
library(MASS)

# covariance matrix for generating factor loadings
#sigma <- matrix(c(0.029, 0.023 , 0.010,
#                  0.023, 0.054, -0.0070,
#                  0.010, -0.0070, 0.086), 3, 3, byrow=TRUE)


# mean for generating factor loadings
#mu11 <- c(0.78, 0.62, 0.21) # small; low b/m
#mu12 <- c(0.78, 0.62, 0.41) # small; mid b/m
#mu13 <- c(0.78, 0.62, 0.61) # small; high b/m
#mu21 <- c(0.78, 0.42, 0.21) # big; low b/m
#mu22 <- c(0.78, 0.42, 0.41) # big; mid b/m
#mu23 <- c(0.78, 0.42, 0.61) # big; high b/m


# covariance matrix for generating factor loadings
#sigma <- matrix(c(0.0073, 0.0058 , 0.0025,
#                  0.0058, 0.014, -0.0018,
#                  0.0025, -0.0018, 0.022), 3, 3, byrow=TRUE)

# mean for generating factor loadings
#mu11 <- c(0.39, 0.31, 0.1) # small; low b/m
#mu12 <- c(0.39, 0.31, 0.2) # small; mid b/m
#mu13 <- c(0.39, 0.31, 0.3) # small; high b/m
#mu21 <- c(0.39, 0.21, 0.1) # big; low b/m
#mu22 <- c(0.39, 0.21, 0.2) # big; mid b/m
#mu23 <- c(0.39, 0.21, 0.3) # big; high b/m


# covariance matrix for generating factor loadings
sigma <- matrix(c(0.0018, 0.0015 , 0.0006,
                  0.0015, 0.0035, -0.0005,
                  0.0006, -0.0005, 0.006), 3, 3, byrow=TRUE)

# mean for generating factor loadings
mu11 <- c(0.2, 0.15, 0.05) # small; low b/m
mu12 <- c(0.2, 0.15, 0.1) # small; mid b/m
mu13 <- c(0.2, 0.15, 0.15) # small; high b/m
mu21 <- c(0.2, 0.1, 0.05) # big; low b/m
mu22 <- c(0.2, 0.1, 0.1) # big; mid b/m
mu23 <- c(0.2, 0.1, 0.15) # big; high b/m



# for each group of assets, generate the factor loadings
l11 <- mvrnorm(n=15, mu=mu11, Sigma=sigma)
l12 <- mvrnorm(n=15, mu=mu12, Sigma=sigma)
l13 <- mvrnorm(n=15, mu=mu13, Sigma=sigma)
l21 <- mvrnorm(n=15, mu=mu21, Sigma=sigma)
l22 <- mvrnorm(n=15, mu=mu22, Sigma=sigma)
l23 <- mvrnorm(n=15, mu=mu23, Sigma=sigma)

loads <- list(l11=l11, l12=l12, l13=l13, l21=l21, l22=l22, l23=l23)
loads

$l11
           [,1]       [,2]         [,3]
 [1,] 0.1786837 0.06947600  0.074194118
 [2,] 0.2213363 0.17979974 -0.040200979
 [3,] 0.2336393 0.25046961  0.064385510
 [4,] 0.1565439 0.16514061 -0.074094276
 [5,] 0.1793966 0.08560445  0.189713504
 [6,] 0.1826560 0.15646189 -0.073222156
 [7,] 0.2325958 0.24661484  0.159878891
 [8,] 0.2035883 0.17831728  0.213599593
 [9,] 0.1897915 0.09841486  0.122871438
[10,] 0.1944923 0.19041914 -0.072695711
[11,] 0.1642550 0.17289571 -0.026762363
[12,] 0.1753135 0.05408189  0.040868887
[13,] 0.2543568 0.09552072  0.040700550
[14,] 0.2525741 0.24353260  0.030896478
[15,] 0.2393322 0.19138508  0.003352883

$l12
           [,1]       [,2]        [,3]
 [1,] 0.1775015 0.19208839  0.04087957
 [2,] 0.1632053 0.12045077  0.02237417
 [3,] 0.1918750 0.15304831  0.14562070
 [4,] 0.1648964 0.07290689  0.12477117
 [5,] 0.1678036 0.14528594  0.08838987
 [6,] 0.1638359 0.15568982  0.11420318
 [7,] 0.1307057 0.09198823  0.08209779
 [8,] 0.1779614 0.11921809  0.16705474
 [9,] 0.2429445 0.17601237  0.05258855
[10,] 0.1530483 0.14535110  0.07138745
[11,] 0.2118587 0.24501258  0.02883815
[12,] 0.2050846 0.15272823  0.03360025
[13,] 0.1824734 0.02650247  0.15108197
[14,] 0.1702839 0.17974733  0.06847880
[15,] 0.1735578 0.20800764 -0.06875888

$l13
           [,1]       [,2]       [,3]
 [1,] 0.2378088 0.14170399 0.30778674
 [2,] 0.1326943 0.10707529 0.17572506
 [3,] 0.1854993 0.17181292 0.31335546
 [4,] 0.2525536 0.20460147 0.18443199
 [5,] 0.2299581 0.22457376 0.20357094
 [6,] 0.2190156 0.19442730 0.24504506
 [7,] 0.2047675 0.08572104 0.08775949
 [8,] 0.1757570 0.12576396 0.04098775
 [9,] 0.1344258 0.06876463 0.24516998
[10,] 0.1843069 0.14066062 0.11204846
[11,] 0.2128843 0.11668353 0.06556129
[12,] 0.2055846 0.17653613 0.23839080
[13,] 0.1583851 0.13418587 0.06452256
[14,] 0.1710866 0.15093038 0.17541212
[15,] 0.2895838 0.25330446 0.05519427

$l21
           [,1]         [,2]        [,3]
 [1,] 0.1476527 -0.009723617  0.10537300
 [2,] 0.1927190  0.019969624  0.02092832
 [3,] 0.2640775  0.204924970  0.03789853
 [4,] 0.2421107  0.046651506  0.19349136
 [5,] 0.1649612  0.071443734 -0.08068800
 [6,] 0.2485352  0.204674960  0.24415331
 [7,] 0.2292325  0.175057916  0.06481214
 [8,] 0.1569462  0.039157929 -0.06402742
 [9,] 0.2738578  0.218943451 -0.03237846
[10,] 0.2287998  0.118584845  0.13654081
[11,] 0.2289789  0.085648747  0.01643199
[12,] 0.2118984  0.112080851  0.17347207
[13,] 0.2504878  0.108801654  0.11897813
[14,] 0.1851736  0.102843684  0.03963171
[15,] 0.2388246  0.063946170  0.10586337

$l22
           [,1]       [,2]         [,3]
 [1,] 0.1626893 0.07748902  0.055999415
 [2,] 0.2249819 0.16995963  0.095645814
 [3,] 0.2136841 0.09552785  0.003582665
 [4,] 0.1565157 0.03678067  0.057986236
 [5,] 0.2249975 0.02500064 -0.012288959
 [6,] 0.1879690 0.13319764  0.045760511
 [7,] 0.2316361 0.09292453  0.143766987
 [8,] 0.2025389 0.08029649  0.107057001
 [9,] 0.1980042 0.14347197  0.138524183
[10,] 0.2567089 0.17337699 -0.022493015
[11,] 0.1391420 0.11394546  0.095879413
[12,] 0.1988651 0.09527739  0.195160695
[13,] 0.2758665 0.13462491  0.166144772
[14,] 0.1103353 0.03327966  0.148211119
[15,] 0.2600931 0.10549914  0.156407750

$l23
            [,1]       [,2]         [,3]
 [1,] 0.19869467 0.10483204  0.331651012
 [2,] 0.22932289 0.12542675  0.172380499
 [3,] 0.27622826 0.15157996  0.209997725
 [4,] 0.24595221 0.18376626  0.271718650
 [5,] 0.13983969 0.13385601 -0.009415589
 [6,] 0.25372232 0.13226238  0.163358167
 [7,] 0.23944992 0.11695287  0.187606851
 [8,] 0.24108149 0.08978312  0.271788212
 [9,] 0.18652974 0.01182407  0.129323633
[10,] 0.07991397 0.04541474 -0.005323974
[11,] 0.15755276 0.01435065  0.106266215
[12,] 0.17575819 0.10914322  0.133056571
[13,] 0.15657779 0.08233095  0.139846071
[14,] 0.32804141 0.19012879  0.238210090
[15,] 0.16876111 0.04415939  0.084944296

In [3]:
loads <- do.call(rbind, loads)
loads

[,1]       [,2]       [,3]        
 [1,] 0.1786837  0.06947600  0.074194118
 [2,] 0.2213363  0.17979974 -0.040200979
 [3,] 0.2336393  0.25046961  0.064385510
 [4,] 0.1565439  0.16514061 -0.074094276
 [5,] 0.1793966  0.08560445  0.189713504
 [6,] 0.1826560  0.15646189 -0.073222156
 [7,] 0.2325958  0.24661484  0.159878891
 [8,] 0.2035883  0.17831728  0.213599593
 [9,] 0.1897915  0.09841486  0.122871438
[10,] 0.1944923  0.19041914 -0.072695711
[11,] 0.1642550  0.17289571 -0.026762363
[12,] 0.1753135  0.05408189  0.040868887
[13,] 0.2543568  0.09552072  0.040700550
[14,] 0.2525741  0.24353260  0.030896478
[15,] 0.2393322  0.19138508  0.003352883
[16,] 0.1775015  0.19208839  0.040879575
[17,] 0.1632053  0.12045077  0.022374174
[18,] 0.1918750  0.15304831  0.145620697
[19,] 0.1648964  0.07290689  0.124771172
[20,] 0.1678036  0.14528594  0.088389870
[21,] 0.1638359  0.15568982  0.114203183
[22,] 0.1307057  0.09198823  0.082097789
[23,] 0.1779614  0.11921809  0.167054739
[24,] 0.2429445  0.17601237  0.052588546
[25,] 0.1530483  0.14535110  0.071387446
[26,] 0.2118587  0.24501258  0.028838154
[27,] 0.2050846  0.15272823  0.033600246
[28,] 0.1824734  0.02650247  0.151081974
[29,] 0.1702839  0.17974733  0.068478796
[30,] 0.1735578  0.20800764 -0.068758876
[31,] ...        ...        ...         
[32,] 0.16268930 0.07748902  0.055999415
[33,] 0.22498194 0.16995963  0.095645814
[34,] 0.21368414 0.09552785  0.003582665
[35,] 0.15651565 0.03678067  0.057986236
[36,] 0.22499746 0.02500064 -0.012288959
[37,] 0.18796902 0.13319764  0.045760511
[38,] 0.23163605 0.09292453  0.143766987
[39,] 0.20253892 0.08029649  0.107057001
[40,] 0.19800422 0.14347197  0.138524183
[41,] 0.25670887 0.17337699 -0.022493015
[42,] 0.13914197 0.11394546  0.095879413
[43,] 0.19886510 0.09527739  0.195160695
[44,] 0.27586655 0.13462491  0.166144772
[45,] 0.11033531 0.03327966  0.148211119
[46,] 0.26009311 0.10549914  0.156407750
[47,] 0.19869467 0.10483204  0.331651012
[48,] 0.22932289 0.12542675  0.172380499
[49,] 0.27622826 0.15157996  0.209997725
[50,] 0.24595221 0.18376626  0.271718650
[51,] 0.13983969 0.13385601 -0.009415589
[52,] 0.25372232 0.13226238  0.163358167
[53,] 0.23944992 0.11695287  0.187606851
[54,] 0.24108149 0.08978312  0.271788212
[55,] 0.18652974 0.01182407  0.129323633
[56,] 0.07991397 0.04541474 -0.005323974
[57,] 0.15755276 0.01435065  0.106266215
[58,] 0.17575819 0.10914322  0.133056571
[59,] 0.15657779 0.08233095  0.139846071
[60,] 0.32804141 0.19012879  0.238210090
[61,] 0.16876111 0.04415939  0.084944296

In [4]:
library(UnivRNG)
library(mvtnorm)

# generate standard deviations for noise
noise <- rgamma(n=90, shape=1, scale=0.01)

# generate noise from t distribution with df=5
noise <- rmvt(n=120, sigma=diag(noise**2), df=5)
noise*100

[,1]          [,2]        [,3]          [,4]         [,5]        
 [1,] -0.008577832  -1.33168394 -0.3099124163 -0.207577940 -0.299715450
 [2,] -0.002892387   0.11958404 -0.0434884783  0.097344183  0.334866395
 [3,]  0.029423712  -1.21285972 -0.3194936785 -0.157848834 -0.018415271
 [4,] -0.011400729  -0.87764980 -0.5346408560 -0.057328536 -0.183339899
 [5,]  0.018838764  -0.11167830  0.0663499714 -0.023716738 -0.172803276
 [6,] -0.027024815   0.42388086 -0.0313860271  0.007382739 -0.136363928
 [7,]  0.009163791   0.42830709  0.0910089837  0.038528305  0.367155231
 [8,] -0.032868424  -0.44297669  0.4445445258  0.260640500  0.144978720
 [9,] -0.041092622   0.09354772 -0.0280673394  0.192979627  0.514890775
[10,]  0.019178718  -0.09470542 -0.3414621583  0.131385668  0.302518437
[11,] -0.078409833  -1.08284519  0.0467653888  0.043276997  0.750778753
[12,]  0.002943237  -0.55268215  0.0593543928 -0.073054165  0.294217911
[13,] -0.028250750   0.31062457  0.3258599096 -0.060583003 -0.237049227
[14,]  0.014493624  -0.66699480 -0.2169241468 -0.200262543 -0.356817553
[15,] -0.008432340   0.23495452  0.0736447196 -0.051571263 -0.072674356
[16,]  0.024263618   0.18903985 -0.0002088473  0.004015756 -0.322273251
[17,]  0.010453127  -0.02410409  0.2394444883 -0.200930595 -0.207163502
[18,]  0.002472312  -0.34502875  0.7241194782 -0.060359297 -0.137170381
[19,]  0.023763400   0.16945259 -0.3454570332 -0.185814943 -0.243703316
[20,] -0.021458103  -0.77279800  0.0308039030  0.039596007  0.503680876
[21,]  0.031591856  -0.17344889 -0.1262407233 -0.044876048  0.144529787
[22,] -0.027621969  -0.74717257 -0.0809761930 -0.106750603 -0.456440748
[23,]  0.009641593  -0.45141129 -0.0772606004  0.083005486 -0.003242045
[24,] -0.002454913   0.14740741  0.0407742612 -0.019626810  0.125305359
[25,] -0.012657959   0.73257668  0.2831213218  0.050767918  0.164800959
[26,]  0.007123621  -0.16622763 -0.2518522858 -0.196481146 -0.019301104
[27,]  0.070630839   0.11019825  0.5154346841  0.109645012  0.027096196
[28,] -0.010066035  -0.11491445 -0.4946700117  0.154408780  0.061032279
[29,]  0.026997573   0.20472535 -0.8492178609  0.137414981 -1.888573136
[30,] -0.051073933  -0.33486581 -0.1049316059  0.074903713 -0.953031645
[31,] ...           ...         ...           ...          ...         
[32,]  0.0110451360 -0.06084817 -0.46148029    0.086869532 -0.507455345
[33,] -0.0243651859 -0.59295318 -0.11608924    0.012104411 -0.792952607
[34,]  0.0166784232  0.64890106  0.45116612    0.056917625 -0.298267314
[35,] -0.0458988451 -1.12436907 -0.32693033   -0.097673580  0.412051196
[36,]  0.0084718457 -0.79000942 -0.17337830    0.010163149 -0.195850951
[37,]  0.0131311596 -0.97335400 -0.51061353    0.080295282 -0.188054708
[38,]  0.0053472661  0.86651252 -0.24069091   -0.047820310 -0.952801812
[39,] -0.0043867401  0.12763844 -0.21562384   -0.089839082 -0.866684757
[40,]  0.0290421498 -0.67121831  0.03783064    0.090548340  1.377784018
[41,] -0.0214006325 -0.03310956 -0.14226176   -0.032755775  0.691103290
[42,]  0.0359645002  0.87140461 -0.27390307    0.147573092  0.430895685
[43,]  0.0122026170 -1.06671479  0.97363821    0.020093021  0.456968535
[44,]  0.0027978030 -0.72799847  0.30658085   -0.020310118  0.433463112
[45,] -0.0169715360 -1.22097809  0.07614493    0.252362020  1.202968335
[46,]  0.0015847031 -0.75508875  0.44007802    0.050669217  0.088704815
[47,] -0.0462628512 -0.26371231  0.26316052   -0.209606125  0.044052673
[48,]  0.0041814498  0.29647725 -0.23486803   -0.028628799 -0.211792536
[49,]  0.0197026626  0.39848199  0.00866590    0.029233272 -0.179743312
[50,]  0.0177073698  0.39272331  0.06502341    0.046343221 -0.053558615
[51,] -0.0007424264  1.60547979 -0.36207869   -0.045023916 -0.404727178
[52,] -0.0194758403  0.15840447 -0.42907031   -0.004186689  0.022621493
[53,]  0.0221656496  1.90125014 -0.14519653    0.005514136 -0.007010514
[54,] -0.0513545868 -0.65114129  1.16496085   -0.106822464 -1.606845492
[55,] -0.0198628804 -0.02397868  0.97028086   

In [5]:
# compute returns
returns <- as.data.frame(as.matrix(fact[,c('mrp', 'smb', 'hml')]) %*% t(loads) + noise)
colnames(returns) <- sprintf('Asset %d', 1:90)

returns

Asset 1       Asset 2       Asset 3       Asset 4       Asset 5      
1    0.0198770080  2.729845e-02  5.194361e-02  0.0331631099  0.0210809728
2    0.0015384172  2.234735e-02  2.157050e-02  0.0231942820 -0.0009530122
3    0.0131041556  3.015739e-02  5.515394e-02  0.0388927792  0.0147212276
4    0.0248660847  1.838457e-02  1.882308e-02  0.0170209269  0.0211381826
5    0.0013440797 -3.071997e-05  8.129157e-03  0.0006582228  0.0040535595
6    0.0113694247  2.763151e-02  2.629477e-02  0.0200953359  0.0090553357
7    0.0031346183  7.767520e-03 -6.212750e-03  0.0023007142 -0.0009148865
8    0.0010037453 -1.380955e-02  3.975954e-05 -0.0079799714  0.0099594789
9    0.0519510946  6.708092e-02  7.376819e-02  0.0493712634  0.0603655394
10   0.0627642087  6.346806e-02  8.735703e-02  0.0428446020  0.0859852923
11   0.0172137220  1.290187e-02  2.714836e-02  0.0178269700  0.0263221245
12  -0.0062403466  3.611667e-03  3.701141e-02  0.0132275140  0.0108276707
13  -0.0091733128 -2.194606e-02 -1.877927e-02 -0.0234607132 -0.0040191551
14  -0.0196220521 -3.809164e-02 -2.641383e-02 -0.0264882328 -0.0149931743
15  -0.0249774490 -1.527387e-02 -2.055221e-02 -0.0080869770 -0.0315225025
16   0.0159473448 -1.443559e-02 -1.298209e-02 -0.0248814980  0.0261010924
17   0.0270281008  6.085922e-03  2.306058e-02 -0.0071960740  0.0429048884
18   0.0020630548  1.139212e-02  2.013336e-02  0.0144448544 -0.0049298545
19   0.0108507789 -3.559205e-03  1.249063e-02 -0.0116638231  0.0289967745
20   0.0666475983  7.928435e-02  1.477170e-01  0.0657925956  0.1106732744
21   0.0165435146  3.220039e-02  3.772532e-02  0.0289199533  0.0159373256
22   0.0316542587  4.072543e-02  5.758045e-02  0.0366011191  0.0303274358
23   0.0031953901  9.807424e-03  1.004390e-02  0.0147530532 -0.0030778917
24   0.0276981727  3.940806e-02  5.207107e-02  0.0284686231  0.0363419695
25   0.0180496280  3.606245e-02  3.411411e-02  0.0232269135  0.0187470884
26   0.0235781920  1.616863e-02  2.095282e-02  0.0065621589  0.0300499933
27   0.0006849912  5.251404e-03  7.882608e-03  0.0055449891 -0.0021589907
28   0.0255506551  8.489974e-02  6.638433e-02  0.0821591892 -0.0035329810
29   0.0614591050  7.534354e-02  8.359178e-02  0.0528688320  0.0538055628
30   0.0118115986  5.539771e-03  9.881857e-03  0.0046846570  0.0058223198
... ...           ...           ...           ...           ...          
91  -0.017903808  -0.039047132  -0.028423027  -0.031738670  -0.006429930 
92   0.021796702   0.008692543   0.018115384   0.005818361   0.020672299 
93   0.026299261   0.019869409   0.027562019   0.003206339   0.035218879 
94   0.029524403   0.014226314   0.028505298   0.012817762   0.041149755 
95   0.019930356   0.018385139   0.034143849   0.019669028   0.023281908 
96   0.016389925   0.013855784   0.026955284   0.019085654   0.018550949 
97   0.041588665   0.052120301   0.061095797   0.027949004   0.047133372 
98   0.023526943   0.033356935   0.024523784   0.022589544   0.009012637 
99   0.011113807  -0.006073134   0.015401686  -0.002891322   0.038659245 
100  0.049089430   0.076504263   0.082537150   0.060101030   0.053820006 
101  0.141352415   0.138714912   0.217514736   0.079905379   0.218368504 
102  0.030024153   0.017252948   0.045669964   0.016758415   0.041892631 
103  0.009745889   0.013650376   0.030188620   0.018173038   0.015075050 
104  0.024088078   0.001796820   0.009529710   0.006109844   0.036794754 
105 -0.036286205  -0.123746992  -0.109956427  -0.108308070  -0.008693710 
106 -0.016490469  -0.030389846  -0.027177405  -0.024736710  -0.013697447 
107  0.022504610   0.053945785   0.055237686   0.044693460   0.016327351 
108  0.015821529   0.007483558   0.016198702  -0.002729859   0.027431136 
109 -0.025024939  -0.058599435  -0.039620836  -0.054564380   0.001766230 
110  0.053001832   0.069117931   0.059005458   0.032578585   0.057606348 
111  0.030048588   0.035883441   0.050600131   0.023782283   0.044883949 
112 -0.013141672   0.012420070  -0.015681224  -0.001132570  -0.021613908 
113 -0.0

In [6]:
# save the simulated returns in a csv file
write.csv(returns, 'returns.csv', row.names=FALSE)