In [1]:
# read the simulated factor values

fact <- read.csv('factors.csv')
head(fact,20)

X  period regime regimeName      mrp         smb          hml        
1   1  1     0      Low Volatility  -0.10299266  0.106877305 -0.01329811
2   2  2     0      Low Volatility   0.12346933  0.040230870  0.11110497
3   3  3     0      Low Volatility  -0.02073444 -0.078870522  0.20442673
4   4  4     0      Low Volatility   0.26491466  0.046289296  0.06745278
5   5  5     0      Low Volatility   0.16227460  0.036609399  0.02742913
6   6  6     0      Low Volatility   0.51069132  0.015935553 -0.04684654
7   7  7     1      High Volatility -0.18789826 -0.316106336 -0.22928204
8   8  8     1      High Volatility  0.16904793  0.059100326  0.30683111
9   9  9     1      High Volatility  0.05728024 -0.126613404  0.12568533
10 10 10     1      High Volatility  0.16206825  0.163061660 -0.01351984
11 11 11     1      High Volatility  0.33916456  0.058431268  0.30895295
12 12 12     1      High Volatility  0.10289185  0.052077549  0.21047236
13 13 13     1      High Volatility -0.01522354  0.481575586  0.49053823
14 14 14     1      High Volatility -0.05473632 -0.294863268  0.31302096
15 15 15     1      High Volatility -0.02868966  0.035067445  0.43880436
16 16 16     1      High Volatility -0.02328092  0.138248723  0.49310879
17 17 17     1      High Volatility  0.16459703  0.121128427  0.17547282
18 18 18     1      High Volatility  0.22014132  0.242919751  0.45966767
19 19 19     1      High Volatility -0.00417564 -0.155584015  0.26492690
20 20 20     0      Low Volatility  -0.00185406 -0.008188082  0.07292379

In [2]:
library(MASS)

# covariance matrix for generating factor loadings
#sigma <- matrix(c(0.029, 0.023 , 0.010,
#                  0.023, 0.054, -0.0070,
#                  0.010, -0.0070, 0.086), 3, 3, byrow=TRUE)


# mean for generating factor loadings
#mu11 <- c(0.78, 0.62, 0.21) # small; low b/m
#mu12 <- c(0.78, 0.62, 0.41) # small; mid b/m
#mu13 <- c(0.78, 0.62, 0.61) # small; high b/m
#mu21 <- c(0.78, 0.42, 0.21) # big; low b/m
#mu22 <- c(0.78, 0.42, 0.41) # big; mid b/m
#mu23 <- c(0.78, 0.42, 0.61) # big; high b/m


# covariance matrix for generating factor loadings
#sigma <- matrix(c(0.0073, 0.0058 , 0.0025,
#                  0.0058, 0.014, -0.0018,
#                  0.0025, -0.0018, 0.022), 3, 3, byrow=TRUE)

# mean for generating factor loadings
#mu11 <- c(0.39, 0.31, 0.1) # small; low b/m
#mu12 <- c(0.39, 0.31, 0.2) # small; mid b/m
#mu13 <- c(0.39, 0.31, 0.3) # small; high b/m
#mu21 <- c(0.39, 0.21, 0.1) # big; low b/m
#mu22 <- c(0.39, 0.21, 0.2) # big; mid b/m
#mu23 <- c(0.39, 0.21, 0.3) # big; high b/m


# covariance matrix for generating factor loadings
sigma <- matrix(c(0.0018, 0.0015 , 0.0006,
                  0.0015, 0.0035, -0.0005,
                  0.0006, -0.0005, 0.006), 3, 3, byrow=TRUE)

# mean for generating factor loadings
mu11 <- c(0.2, 0.15, 0.05) # small; low b/m
mu12 <- c(0.2, 0.15, 0.1) # small; mid b/m
mu13 <- c(0.2, 0.15, 0.15) # small; high b/m
mu21 <- c(0.2, 0.1, 0.05) # big; low b/m
mu22 <- c(0.2, 0.1, 0.1) # big; mid b/m
mu23 <- c(0.2, 0.1, 0.15) # big; high b/m



# for each group of assets, generate the factor loadings
l11 <- mvrnorm(n=15, mu=mu11, Sigma=sigma)
l12 <- mvrnorm(n=15, mu=mu12, Sigma=sigma)
l13 <- mvrnorm(n=15, mu=mu13, Sigma=sigma)
l21 <- mvrnorm(n=15, mu=mu21, Sigma=sigma)
l22 <- mvrnorm(n=15, mu=mu22, Sigma=sigma)
l23 <- mvrnorm(n=15, mu=mu23, Sigma=sigma)

loads <- list(l11=l11, l12=l12, l13=l13, l21=l21, l22=l22, l23=l23)
loads

$l11
           [,1]       [,2]         [,3]
 [1,] 0.2280371 0.16351311  0.113203590
 [2,] 0.2353384 0.12571111  0.137111563
 [3,] 0.1970524 0.23022754 -0.014876733
 [4,] 0.2364817 0.13203414  0.093883913
 [5,] 0.2239975 0.06626652  0.245064735
 [6,] 0.2092392 0.12645151  0.115577066
 [7,] 0.1640316 0.07213460  0.193589658
 [8,] 0.2397748 0.17164708  0.147714212
 [9,] 0.1317601 0.07677753  0.104688876
[10,] 0.2229463 0.19461010  0.065505927
[11,] 0.2620747 0.14276811  0.079541892
[12,] 0.2123421 0.10804959  0.077333977
[13,] 0.1886096 0.15946021  0.272731161
[14,] 0.1624398 0.10320587  0.122252615
[15,] 0.2010203 0.16427592  0.007542496

$l12
           [,1]       [,2]        [,3]
 [1,] 0.1495564 0.11963168 0.107407772
 [2,] 0.2811253 0.18784057 0.117218999
 [3,] 0.1807906 0.09662246 0.108753651
 [4,] 0.1320889 0.07873576 0.040898867
 [5,] 0.1326226 0.11787631 0.051546583
 [6,] 0.1330827 0.12051499 0.004622706
 [7,] 0.1963597 0.12590568 0.162959000
 [8,] 0.2939544 0.20133263 0.189264583
 [9,] 0.2193343 0.16945639 0.225871233
[10,] 0.1527842 0.07622265 0.145444561
[11,] 0.1740726 0.12391584 0.046924860
[12,] 0.2086878 0.14520271 0.044938552
[13,] 0.1636220 0.15394545 0.074971095
[14,] 0.1782588 0.06066943 0.197852207
[15,] 0.1996935 0.11338611 0.039664428

$l13
           [,1]       [,2]       [,3]
 [1,] 0.2442496 0.21344959 0.15105548
 [2,] 0.1973372 0.20485772 0.18278890
 [3,] 0.1688435 0.11350624 0.16757078
 [4,] 0.2419827 0.22258428 0.19749479
 [5,] 0.2121014 0.18936452 0.26639246
 [6,] 0.2300668 0.10375839 0.12094711
 [7,] 0.2492279 0.13915021 0.02557800
 [8,] 0.1135765 0.04478107 0.16365274
 [9,] 0.2022052 0.12794598 0.17553557
[10,] 0.2598021 0.17815745 0.30647514
[11,] 0.2333692 0.10909540 0.13545023
[12,] 0.1907449 0.22215818 0.19685027
[13,] 0.1886215 0.14607689 0.06976151
[14,] 0.2345649 0.14506939 0.06861931
[15,] 0.2740446 0.22599596 0.11903338

$l21
           [,1]        [,2]         [,3]
 [1,] 0.2207686  0.14200291  0.096721414
 [2,] 0.2128494  0.13939156  0.099182252
 [3,] 0.1549597  0.08042833  0.092457813
 [4,] 0.2384713  0.07835422 -0.070591310
 [5,] 0.1608351  0.07897282  0.088863286
 [6,] 0.1550542 -0.01063269  0.019584999
 [7,] 0.1232369  0.12604857 -0.063644823
 [8,] 0.2146940  0.14271351 -0.001626958
 [9,] 0.1663105  0.09905459  0.032584007
[10,] 0.2553321  0.11752615  0.128126041
[11,] 0.1783753  0.10861518  0.078629490
[12,] 0.2659673  0.16880501 -0.152188614
[13,] 0.2151090  0.11807591  0.063939588
[14,] 0.2355440  0.16147129  0.025495261
[15,] 0.2773278  0.14623807  0.074273879

$l22
           [,1]         [,2]       [,3]
 [1,] 0.1927622  0.064809778 0.18430764
 [2,] 0.1491999  0.009800793 0.03074421
 [3,] 0.2431810 -0.001519093 0.16227831
 [4,] 0.1830225  0.143690048 0.17458249
 [5,] 0.1572413 -0.053151654 0.21013104
 [6,] 0.2263953  0.119654812 0.08912208
 [7,] 0.2472993  0.137611175 0.17007476
 [8,] 0.2069214  0.136587759 0.10179904
 [9,] 0.2128385  0.050042051 0.20473259
[10,] 0.2037933  0.061443040 0.06218291
[11,] 0.2209193  0.148735948 0.07903261
[12,] 0.1450795  0.052656205 0.16285185
[13,] 0.1505759  0.047137306 0.12456606
[14,] 0.2493256  0.062366222 0.14668419
[15,] 0.2376215  0.157499185 0.10073506

$l23
           [,1]        [,2]        [,3]
 [1,] 0.1621110 0.003297283  0.26976959
 [2,] 0.2219704 0.027522694  0.10617173
 [3,] 0.2137057 0.109008812  0.10911759
 [4,] 0.2565589 0.192184722  0.16948850
 [5,] 0.2297720 0.118696914 -0.07408647
 [6,] 0.1305721 0.026581573  0.21473506
 [7,] 0.1657572 0.184046329  0.06383240
 [8,] 0.2737981 0.173884670  0.20197494
 [9,] 0.2539021 0.191442217  0.11873198
[10,] 0.1778297 0.023901164  0.14268354
[11,] 0.1722519 0.156648790  0.14123575
[12,] 0.1963622 0.083670788  0.10488113
[13,] 0.1988155 0.143336206  0.12580490
[14,] 0.2297594 0.133222305  0.16349264
[15,] 0.2593496 0.184367839  0.04565981

In [3]:
loads <- do.call(rbind, loads)
loads

[,1]      [,2]         [,3]        
 [1,] 0.2280371 0.16351311    0.113203590
 [2,] 0.2353384 0.12571111    0.137111563
 [3,] 0.1970524 0.23022754   -0.014876733
 [4,] 0.2364817 0.13203414    0.093883913
 [5,] 0.2239975 0.06626652    0.245064735
 [6,] 0.2092392 0.12645151    0.115577066
 [7,] 0.1640316 0.07213460    0.193589658
 [8,] 0.2397748 0.17164708    0.147714212
 [9,] 0.1317601 0.07677753    0.104688876
[10,] 0.2229463 0.19461010    0.065505927
[11,] 0.2620747 0.14276811    0.079541892
[12,] 0.2123421 0.10804959    0.077333977
[13,] 0.1886096 0.15946021    0.272731161
[14,] 0.1624398 0.10320587    0.122252615
[15,] 0.2010203 0.16427592    0.007542496
[16,] 0.1495564 0.11963168    0.107407772
[17,] 0.2811253 0.18784057    0.117218999
[18,] 0.1807906 0.09662246    0.108753651
[19,] 0.1320889 0.07873576    0.040898867
[20,] 0.1326226 0.11787631    0.051546583
[21,] 0.1330827 0.12051499    0.004622706
[22,] 0.1963597 0.12590568    0.162959000
[23,] 0.2939544 0.20133263    0.189264583
[24,] 0.2193343 0.16945639    0.225871233
[25,] 0.1527842 0.07622265    0.145444561
[26,] 0.1740726 0.12391584    0.046924860
[27,] 0.2086878 0.14520271    0.044938552
[28,] 0.1636220 0.15394545    0.074971095
[29,] 0.1782588 0.06066943    0.197852207
[30,] 0.1996935 0.11338611    0.039664428
[31,] ...       ...          ...         
[32,] 0.1927622  0.064809778  0.18430764 
[33,] 0.1491999  0.009800793  0.03074421 
[34,] 0.2431810 -0.001519093  0.16227831 
[35,] 0.1830225  0.143690048  0.17458249 
[36,] 0.1572413 -0.053151654  0.21013104 
[37,] 0.2263953  0.119654812  0.08912208 
[38,] 0.2472993  0.137611175  0.17007476 
[39,] 0.2069214  0.136587759  0.10179904 
[40,] 0.2128385  0.050042051  0.20473259 
[41,] 0.2037933  0.061443040  0.06218291 
[42,] 0.2209193  0.148735948  0.07903261 
[43,] 0.1450795  0.052656205  0.16285185 
[44,] 0.1505759  0.047137306  0.12456606 
[45,] 0.2493256  0.062366222  0.14668419 
[46,] 0.2376215  0.157499185  0.10073506 
[47,] 0.1621110  0.003297283  0.26976959 
[48,] 0.2219704  0.027522694  0.10617173 
[49,] 0.2137057  0.109008812  0.10911759 
[50,] 0.2565589  0.192184722  0.16948850 
[51,] 0.2297720  0.118696914 -0.07408647 
[52,] 0.1305721  0.026581573  0.21473506 
[53,] 0.1657572  0.184046329  0.06383240 
[54,] 0.2737981  0.173884670  0.20197494 
[55,] 0.2539021  0.191442217  0.11873198 
[56,] 0.1778297  0.023901164  0.14268354 
[57,] 0.1722519  0.156648790  0.14123575 
[58,] 0.1963622  0.083670788  0.10488113 
[59,] 0.1988155  0.143336206  0.12580490 
[60,] 0.2297594  0.133222305  0.16349264 
[61,] 0.2593496  0.184367839  0.04565981

In [4]:
library(UnivRNG)
library(mvtnorm)

# generate standard deviations for noise
noise <- rgamma(n=90, shape=1, scale=0.01)
#noise <- draw.left.truncated.gamma(nrep=90, alpha=3.3586, beta=0.1876, tau=0.195)$y

# generate noise from t distribution with df=5
noise <- rmvt(n=120, sigma=diag(noise**2), df=5)
noise*100

[,1]         [,2]        [,3]          [,4]        [,5]       
 [1,]  0.226009594  0.06331714 -0.023813343   0.64139911 -1.0686367 
 [2,] -0.056449987  0.35010260 -0.050411524   2.51115712 -1.4621841 
 [3,]  0.288234523 -0.13946407  0.024792820   0.02316098  0.8917037 
 [4,]  0.408542113  0.17448735  0.015732815   4.00220951 -4.9534342 
 [5,]  0.361037408  0.23975601  0.034211657  -3.33512224 -4.2032218 
 [6,] -0.568248842 -1.23050754  0.087005791   8.38582854  3.4357550 
 [7,]  0.212828713 -0.07869894  0.067279601   3.10272825 -1.2537894 
 [8,]  0.589113578 -0.23759779 -0.106054282  -1.28472650  4.7987827 
 [9,] -0.186219575  0.39451889 -0.023722236  -0.74556973  4.2231956 
[10,]  0.152282916  1.90154003  0.009365549   5.23158792  6.5847827 
[11,] -0.518308507  0.44115217 -0.018518491   3.62716000  1.9532280 
[12,] -0.089217688  0.27556122 -0.029785577  -3.59951133 -1.1847419 
[13,] -0.266312670  0.42395022 -0.076833126   4.58848818  5.5666994 
[14,]  0.323026488 -1.43213711 -0.030581446  -6.95568239 10.7730175 
[15,]  0.538546252 -0.07491413 -0.079800456   2.65462862  3.0795068 
[16,] -0.006103908  0.79633527  0.031903200  -1.36879200 -0.8808909 
[17,] -0.469004752 -0.25702104 -0.028162100   0.51872485 -2.2148203 
[18,]  0.005569747 -0.27191350 -0.048684909  -0.38283688  1.7129761 
[19,]  0.251208593 -1.01516549  0.039295889  -0.47276851  2.2354802 
[20,]  0.049048869 -0.07332348  0.005697748  -4.62934118 -2.1278795 
[21,]  0.130598527  0.67724354 -0.094957235  -4.05739377 -1.2568838 
[22,] -0.107514148 -0.23874998  0.020419479  -0.63575312  2.6794407 
[23,]  0.217569664  0.41760782  0.002854147   0.32307110 -1.0297526 
[24,]  0.059436877  0.34663333  0.084605827  -2.41518725 -0.3160163 
[25,]  0.266427244  0.26351343  0.026653745  -2.69637490  1.4677281 
[26,] -0.073469985 -0.59787072  0.054373864  -4.31835825 -0.8445402 
[27,]  0.867100454 -2.33229926 -0.105002405  13.25082431  0.4623902 
[28,]  0.140774608  1.25292884  0.024328794  -3.46782502 -4.4688524 
[29,]  0.006979687 -0.11156670 -0.040269457  -7.75619359 -2.5742197 
[30,] -0.006118406 -0.25830755  0.018056472   2.46899547  0.6926333 
[31,] ...          ...         ...           ...         ...        
[32,]  0.012010685  0.54747208  0.0342943696   1.7611491 -5.77118275
[33,] -0.269399247  0.38879248  0.0200424893   5.1085702 -0.48964310
[34,]  0.594152826 -2.14358868 -0.0322416875   2.4590832  1.00787559
[35,] -0.070272086 -0.02941931 -0.0593499384  -2.3451180  0.32184427
[36,]  0.060410182 -0.19212526 -0.0697098268  -1.0928563 -4.93189608
[37,]  0.141581967  0.55135003  0.1090289099   1.7898248  0.54886628
[38,]  0.079032777  0.12892505  0.0272313804   4.9485279  2.93742967
[39,]  0.450202020 -0.18421238 -0.0026574536 -11.5839313 -4.01698628
[40,] -0.337629328  0.72755792  0.0515664086   6.3652013  5.13735316
[41,]  0.237373150 -0.56969029 -0.0009573479   1.1484016 -0.10151665
[42,]  0.028541333 -0.35858173  0.0230063471   1.3885875 -0.68882942
[43,] -0.229731580 -0.24088239 -0.0640284007   2.3095069 -0.17004607
[44,] -0.288657063  0.34801414  0.0316097991   5.8041480 -3.46459742
[45,]  0.151706599 -0.35114120  0.0668494102  -0.2651521 -0.45737638
[46,]  0.395113773 -0.80762047 -0.0528827665  -7.0615936  2.56282039
[47,] -0.113206266 -0.08744035  0.0024694726   1.6853909  1.62492771
[48,]  0.141801800  0.09451062  0.0016152832  -4.0852495 -3.74817685
[49,] -0.269922294  1.21518270 -0.0271761056 -15.2614785 12.26129417
[50,]  0.859813235  0.65939556 -0.0890088592  -9.1849347  2.21506702
[51,] -0.031200473 -0.61044286 -0.0367159126  -1.4705947 -2.92366366
[52,] -0.008369928 -0.35681407  0.0421426487   0.5350399 -3.73810148
[53,] -0.163183730 -0.59443433 -0.0077675072   1.6692041 -2.32995524
[54,]  0.116876065  0.26948956  0.0480864623  -5.2956488 -3.01577761
[55,] -0.284813802  0.29268384  0.0395288907  -3.2262385 -2.99632805
[56,]  0.482138521 -0.06626623 -0.0201716483   2.7938715  4.15311856
[57,]  0.284566035 -0.87113638 -0.0029492850   0.8430991 -0.47229795
[58,

In [5]:
# compute returns
returns <- as.data.frame(1:120)
returns <- do.call(cbind, list(1:120, as.matrix(fact[,c('mrp', 'smb', 'hml')]) %*% t(loads) + noise))
colnames(returns) <- c('Period', 1:90)

returns

Period 1            2            3             4            5           
 [1,]  1     -0.005255603 -0.011992615  0.0042708445 -0.005078913 -0.029932979
 [2,]  2      0.046746841  0.052849343  0.0314351905  0.070052625  0.042928855
 [3,]  3      0.008399599  0.011840116 -0.0250372123  0.004107073  0.049143880
 [4,]  4      0.079700586  0.079157096  0.0620129960  0.115114058  0.029403613
 [5,]  5      0.049706192  0.048950063  0.0403391563  0.012432595  0.003464782
 [6,]  6      0.108076541  0.103460272  0.1058687456  0.202333333  0.138326705
 [7,]  7     -0.118362562 -0.116181962 -0.1057184287 -0.076669941 -0.131762851
 [8,]  8      0.088838393  0.086907151  0.0412926398  0.063739242  0.164964005
 [9,]  9      0.004724902  0.018741628 -0.0199696932  0.001172568  0.077473401
[10,] 10      0.063612622  0.075801217  0.0697720126  0.110902463  0.109643006
[11,] 11      0.116687870  0.133936445  0.0755042895  0.153198443  0.175089814
[12,] 12      0.054912568  0.062374935  0.0288357776  0.014972909  0.066230453
[13,] 13      0.128139950  0.128454684  0.0998061899  0.151922861  0.204382918
[14,] 14     -0.022030558 -0.021351725 -0.0836341135 -0.092045348  0.152640211
[15,] 15      0.054251372  0.057072599 -0.0049058549  0.065588477  0.134227926
[16,] 16      0.073057212  0.087474777  0.0202242868  0.045355104  0.115981060
[17,] 17      0.072514415  0.075452331  0.0574292589  0.076578595  0.065750085
[18,] 18      0.142012673  0.142652033  0.0919809943  0.123460123  0.195186655
[19,] 19      0.006110536  0.005631558 -0.0401908330 -0.001385176  0.076033698
[20,] 20      0.006984070  0.007799796 -0.0032783593 -0.040966599 -0.004365646
[21,] 21      0.017183111  0.028625651 -0.0007998969 -0.020662548  0.017882908
[22,] 22      0.051483364  0.042550819  0.0696313591  0.042819903  0.051981918
[23,] 23      0.005489373  0.010785906 -0.0058558195  0.008194363  0.002673784
[24,] 24      0.031557659  0.029235256  0.0449371798  0.005213299  0.007943653
[25,] 25      0.042004161  0.045648627  0.0265441283  0.014350034  0.062058720
[26,] 26      0.066780195  0.059329426  0.0624820350  0.019861097  0.055154402
[27,] 27      0.038618741  0.006987815  0.0249330838  0.162389621  0.034157852
[28,] 28     -0.023792327 -0.018064742 -0.0002307011 -0.057930165 -0.094430825
[29,] 29      0.028438328  0.028918879  0.0281402805 -0.044225549 -0.003281071
[30,] 30     -0.055647426 -0.054939261 -0.0621154038 -0.030861577 -0.031753707
[31,] ...    ...          ...          ...           ...          ...         
[32,]  91     0.025357632  0.032103844  0.021087254   0.044375046 -0.031821131
[33,]  92     0.026568308  0.034814272  0.015919696   0.077371745  0.035626734
[34,]  93    -0.043155252 -0.065278803 -0.046091523  -0.014107212 -0.036775492
[35,]  94     0.054630583  0.052542150  0.040558408   0.021195990  0.067768772
[36,]  95     0.136226649  0.132755720  0.098228202   0.108110390  0.109182530
[37,]  96     0.072938174  0.080598735  0.037746372   0.080072471  0.106973875
[38,]  97     0.096625221  0.102334408  0.069899448   0.145637978  0.139270993
[39,]  98     0.045767991  0.041096469  0.032999101  -0.073848873  0.003544134
[40,]  99    -0.084270463 -0.073627522 -0.067020036  -0.013504494 -0.032154619
[41,] 100     0.048024379  0.036730445  0.055814364   0.058636328  0.025100293
[42,] 101    -0.005259778 -0.010592742  0.003846230   0.010364712 -0.022418013
[43,] 102     0.034958410  0.033323895  0.030068452   0.055231024  0.037904478
[44,] 103     0.024791912  0.029648360  0.028122080   0.084035758 -0.011368109
[45,] 104     0.038503733  0.035255843  0.031650145   0.036372090  0.032745727
[46,] 105     0.083146386  0.070421029  0.079435004   0.011513235  0.090209518
[47,] 106    -0.010096773 -0.006720653 -0.014900503   0.010444886  0.015087888
[48,] 107     0.051757783  0.052904203  0.045178136   0.012334584  0.009863853
[49,] 108     0.003928748  0.024289582 -0.014589857  -0.146417201  0.152228569
[50,] 109     0.025205544  0.021445370  0.024247295  -0.

In [6]:
# save the simulated returns in a csv file
write.csv(returns, 'returns.csv')